#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$SCRIPT_DIR"
if [ -z "$GITPOD_WORKSPACE_ID" ]; then
  unset GOPATH
fi
go build -o relay svc/relay/main.go
go build -o mapdump cmd/mapdump/main.go
