#!/usr/bin/env bash

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$SCRIPT_DIR"
if [ -z "$GITPOD_WORKSPACE_ID" ]; then
  unset GOPATH
fi

go build -o cluster svc/cluster/main.go
go build -o sourdump cmd/sourdump/main.go
