#!/usr/bin/env bash

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DIST_DIR="$SCRIPT_DIR/../dist"
SRC_DIR="$SCRIPT_DIR/../src"

mkdir -p "$DIST_DIR"

# Ensures that a symlink exists from $2 to $1.
ensure_link() {
  if [ ! -L "$2" ] || [ ! "$(readlink $2)" -ef "$1" ]; then
    rm -rf "$2"
    ln -s "$1" "$2"
  fi
}

SITE_DIR="$SCRIPT_DIR/../../pkg/server/static/site"
mkdir -p "$SITE_DIR"

cd "$SCRIPT_DIR/../"

cp "$SRC_DIR/index.html" "$SITE_DIR/index.html"
cp "$SRC_DIR/favicon.ico" "$SITE_DIR/favicon.ico"
cp "$SRC_DIR/background.png" "$SITE_DIR/background.png"
cp -r "$SRC_DIR/../../game/dist/game" "$SITE_DIR"
yarn serve:site
