image:
  file: gitpod/Dockerfile

tasks:
  - name: Ingress
    init: >
      git lfs pull &&
      /usr/bin/gp sync-done lfs
    command: ./services/ingress/build

  - name: WebSocket proxy
    init: ./services/proxy/build
    command: ./watch /workspace/sour/services/proxy ./wsproxy 28785

  - name: Game server
    init: /usr/bin/gp sync-await lfs && ./services/go/build
    command: ./watch /workspace/sour/services/go ./cluster

  - name: Config
    init: ./config/build
    command: CONFIG=1 ./watch /workspace/sour/config cat

  - name: Redis
    command: /usr/local/bin/redis-server /workspace/sour/services/redis/redis.conf

  - name: Client
    init: >
      /usr/bin/gp sync-await lfs &&
      cd services/client &&
      yarn install
    command: /workspace/sour/services/client/build

  - name: Assets
    env:
      ASSET_OUTPUT_DIR: /workspace/sour/build/assets
    init: >
      /usr/bin/gp sync-await lfs &&
      ./services/assets/build
    command: ./watch /workspace/sour/services/assets cat

  - name: Sauerbraten
    init: >
      /usr/bin/gp sync-await lfs &&
      ./services/game/build
    env:
      GAME_OUTPUT_DIR: /workspace/sour/build/game
    command: ./watch /workspace/sour/services/game cat

ports:
  - port: 1234
    onOpen: open-preview
    visibility: public

  - port: 28785
    onOpen: ignore
    visibility: public
