#!/usr/bin/env bash

set -e

CONFIG_DIR=${CONFIG_DIR:-/sour/config}

# Validate the user's configuration and export the combined config
export SOUR_CONFIG=$(cue export /sour/schema.cue /sour/default-config.yaml $CONFIG_DIR/*.{json,yaml,cue})

if [ -z "$SOUR_CONFIG" ]; then
  echo "A Sour config must be defined."
fi

# Update env vars in the source code
(cd /app/ && sed -i -e "s{__SOUR_CONFIG__{$SOUR_CONFIG{g" index.js)

run_proxy() {
  wsproxy 28785
}

run_cluster() {
  cd /qserv
  cluster
}

run_site() {
  nginx -g 'daemon off;'
}

run_proxy &
run_cluster &
run_site &

tail -F /bin/entrypoint
