#!/usr/bin/env bash

set -e

CONFIG_DIR=${CONFIG_DIR:-/sour/config}

mkdir -p "$CONFIG_DIR"

# Validate the user's configuration and export the combined config
export SOUR_CONFIG=$(cue export /sour/schema.cue /sour/default-config.yaml $(find $CONFIG_DIR -name '*.json' -or -name '*.yaml' -or -name '*.cue'))

if [ -z "$SOUR_CONFIG" ]; then
  echo "A Sour config must be defined."
fi

# Inject the runtime configuration into the frontend's code
echo "const INJECTED_SOUR_CONFIG = $SOUR_CONFIG;" >> /tmp/out.js
cat /app/index.js >> /tmp/out.js
cp /tmp/out.js /app/index.js

wsproxy 28785 &
cluster &
nginx -g 'daemon off;' &

tail -F /bin/entrypoint
