#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Prefixed to filenames
HASH="$1"

# The actual output directory
OUTPUT_DIR="$SCRIPT_DIR/output"
mkdir -p "$OUTPUT_DIR"

# Contains all of the interim calculations
WORKING_DIR="$SCRIPT_DIR/working"
mkdir -p "$WORKING_DIR"

# /home/gitpod/emsdk
EMSDK_DIR=${EMSDK:-/emsdk}

package_files() {
  target="$1"
	shift 1
	files="$@"

  target_dir="$WORKING_DIR/$target"

  echo "Packaging $HASH.$target.data"

	# Preprocess the files
	for infile in $files; do
    outfile="$target_dir/$infile"
    extension="${infile##*.}"
    size=$(wc -c "$infile" | cut -f1 -d' ')

    if ! [ -f "$infile" ] || [ -f "$outfile" ]; then
      continue
    fi

    mkdir -p "$(dirname "$outfile")"

    if [ "$extension" != "dds" ] && [ "$extension" != "jpg" ] && [ "$extension" != "png" ]; then
      cp "$infile" "$outfile"
      continue
    fi

    # Ignore small files and anything in data/ since those are the game's basic assets
    if [[ "$size" -lt 128000 ]] || [[ "$infile" == data* ]]; then
      cp "$infile" "$outfile"
      continue
    fi

    # Simplify the file
    convert "$infile" -resize 50% "$outfile"
    convert "$outfile" -resize 50% "$outfile"
	done

	# Package the files up
  cd "$target_dir"
  js_target="$OUTPUT_DIR/$HASH.preload_$target.js"
  python3 "$EMSDK_DIR/upstream/emscripten/tools/file_packager.py" \
					"$OUTPUT_DIR/$HASH.$target.data" \
					--use-preload-plugins \
					--preload $files > "$js_target"

  # Insert our _free() hack
  sed -i '/getMemory/a Module["registerNode"]({ name: REMOTE_PACKAGE_BASE, pointer: ptr, files: metadata["files"] });' "$js_target"
  cd "$SCRIPT_DIR"
}

package_map() {
  target="$1"

  mapname="$(basename -s .ogz "$target")"
  maplist="mapfiles/maps/$mapname.list"

  if ! [ -f "$maplist" ]; then
    return
  fi

  package_files "$mapname" $(cat $maplist)
}

maps=$(find packages/base/ -name '*.ogz')
maps="packages/base/xenon.ogz packages/base/complex.ogz"

for map in $maps; do
  mapfile=$(basename -s .ogz "$map")
  mapstub="packages/base/$mapfile.stub"
  touch "$mapstub"
  echo "$mapstub" >> mapfiles/maps.list
done

package_files base $(cat mapfiles/maps.list mapfiles/common.trimmed.list)

for map in $maps; do
  mapfile=$(basename -s .ogz "$map")
  package_map "$map" &
done

wait
