#!/usr/bin/env bash

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$SCRIPT_DIR"

paths="schema.cue config.yaml"
if [ -f "private.cue" ]; then
  paths+=" private.cue"
fi
cue export -sE --strict $paths > config.json
