#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$SCRIPT_DIR"

set -e

mkdir -p cache

outdir=${ASSET_OUTPUT_DIR:-output}

./setup

echo "building desktop"
./sourdump base \
  --game-root https://static.sourga.me/blobs/6481/.index.source \
  --models \
  --textures \
  --outdir $outdir/desktop \
  complex dust2 turbine

echo "building mobile"
./sourdump base \
  --game-root https://static.sourga.me/blobs/6481/.index.source \
  --mobile \
  --outdir $outdir/mobile \
  none
