#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$SCRIPT_DIR"

set -e

mkdir -p cache

./setup

outdir=${ASSET_OUTPUT_DIR:-output}

./sourdump base \
  --game-root https://static.sourga.me/blobs/6481/.index.source \
  --models \
  --download \
  --outdir dist \
  complex dust2 turbine
