#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$SCRIPT_DIR"

set -e

mkdir -p cache

if ! [ -f "sourdump" ]; then
  cd ..
  go build -o assets/sourdump ./cmd/sourdump
  cd assets
fi
