#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Janky as heck but here we are
SAUERBRATEN="$1"
EXE_PATH="$2"

for f in $(find ../packages/base -name '*.ogz'); do
  mapfile=$(basename -s .ogz "$f")
  outfile="maps/$mapfile.list"

  if [ -f "$outfile" ]; then
    continue
  fi

  current=$(pwd)
  cd "$SAUERBRATEN"
  strace -e trace=open,openat,close,read -o "$current/$mapfile.strace" \
    "$EXE_PATH" \
    "-l$mapfile" \
    -x"quit"

  cd "$current"

  cat "$mapfile.strace" | perl -n -e'/open\("(?!\/)(.+)"/ && print "$1\n"' | sort -u > "$mapfile.raw"
  comm -23 "$mapfile.raw" common.list > "$outfile"
  rm "$mapfile.strace"
done
