#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$SCRIPT_DIR/../"

set -e

cd "$SCRIPT_DIR/src/web"

# When you restart the container, this is not there
if ! [ -f "/emsdk/upstream/emscripten/cache/wasm/libz.a" ]; then
  emmake make clean
fi

emmake make client -j8
cd "$SCRIPT_DIR"

OUTPUT_DIR=${GAME_OUTPUT_DIR:-dist/game}
mkdir -p "$OUTPUT_DIR"
# Need to get rid of some unseemly behavior
patch sauerbraten.js file_create.patch
cp -r \
  js/api.js \
  js/zee.js \
  game/zee-worker.js \
  game/gl-matrix.js \
  sauerbraten.* \
  "$OUTPUT_DIR"
