#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$SCRIPT_DIR"

set -e

mkdir -p cache

if ! pip3 list | grep "cbor2" > /dev/null 2>&1; then
  pip3 install -r requirements.txt
fi

#sauer_archive="sauerbraten-6481.tar.gz"

#mkdir -p roots/base/

#if ! [ -f "roots/base/$sauer_archive" ]; then
  #wget "https://static.sourga.me/archives/$sauer_archive"
  #mv "$sauer_archive" roots/base/
#fi

#if ! [ -f "roots/base/data/default_map_settings.cfg" ]; then
  #tar xvf "roots/base/$sauer_archive" -C "roots/base" 
#fi

if ! [ -f "sourdump" ]; then
  cd ../go
  go build -o sourdump cmd/sourdump/main.go
  mv sourdump ../assets
fi
